name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      KUBECONFIG: $HOME/.kube/config

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ steps.vars.outputs.TAG }} ./k8s
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ steps.vars.outputs.TAG }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Debug secret length
        run: echo "${{ secrets.KUBECONFIG }}" | wc -c

      - name: Check cluster
        run: kubectl get nodes

      - name: Helm upgrade
        run: |
          helm upgrade --install demo-app ./chart \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/demo-app \
            --set image.tag=${{ steps.vars.outputs.TAG }} \
            --atomic \
            --wait

